
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-5', 'gcc-5', 'expat', 'libgmp-dev']

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - export GCCVER='5'
  - export CXX=g++-${GCCVER}
  - export CC=gcc-${GCCVER}
  - export AR=gcc-ar-${GCCVER}
  - export RANLIB=gcc-ranlib-${GCCVER}
  - export NM=gcc-nm-${GCCVER}

# build spot
script :
  - ./tag.sh
  - ./build_spot.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: website/
  upload-dir: build/$TRAVIS_BUILD_NUMBER
  on:
    branch: master
  
