dist: trusty
sudo: false


language : python

script :
  - ./tag.sh
  - ./build_z3.sh
  - ls -lah website/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: website/
  on:
    branch: master
  
after_deploy:
  - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json"   -H "Travis-API-Version:3" -H "Authorization:token $APITOKEN" -d '{"request":{"message":"Triggered by ITS Tools Dependencies build.","branch":"master"}}' https://api.travis-ci.org/repo/lip6%2FITS-Tools/requests
